use crate::test::snapshot_inner;
use test_case::test_case;
#[test_case(r#####"import { globalStyles } from '../macro'"#####, r#####";"##### ; "0")]
#[test_case(r#####"globalStyles"#####, r#####"({
  '*, ::before, ::after': {
    '--tw-border-spacing-x': "0",
    '--tw-border-spacing-y': "0",
    '--tw-translate-x': "0",
    '--tw-translate-y': "0",
    '--tw-rotate': "0",
    '--tw-skew-x': "0",
    '--tw-skew-y': "0",
    '--tw-scale-x': "1",
    '--tw-scale-y': "1",
    '--tw-pan-x': "var(--tw-empty,/*!*/ /*!*/)",
    '--tw-pan-y': "var(--tw-empty,/*!*/ /*!*/)",
    '--tw-pinch-zoom': "var(--tw-empty,/*!*/ /*!*/)",
    '--tw-scroll-snap-strictness': "proximity",
    '--tw-ordinal': "var(--tw-empty,/*!*/ /*!*/)",
    '--tw-slashed-zero': "var(--tw-empty,/*!*/ /*!*/)",
    '--tw-numeric-figure': "var(--tw-empty,/*!*/ /*!*/)",
    '--tw-numeric-spacing': "var(--tw-empty,/*!*/ /*!*/)",
    '--tw-numeric-fraction': "var(--tw-empty,/*!*/ /*!*/)",
    '--tw-ring-offset-shadow': "0 0 #0000",
    '--tw-ring-shadow': "0 0 #0000",
    '--tw-shadow': "0 0 #0000",
    '--tw-shadow-colored': "0 0 #0000",
    '--tw-ring-inset': "var(--tw-empty,/*!*/ /*!*/)",
    '--tw-ring-offset-width': "0px",
    '--tw-ring-offset-color': "#fff",
    '--tw-ring-color': "rgb(59 130 246 / 0.5)",
    '--tw-blur': "var(--tw-empty,/*!*/ /*!*/)",
    '--tw-brightness': "var(--tw-empty,/*!*/ /*!*/)",
    '--tw-contrast': "var(--tw-empty,/*!*/ /*!*/)",
    '--tw-grayscale': "var(--tw-empty,/*!*/ /*!*/)",
    '--tw-hue-rotate': "var(--tw-empty,/*!*/ /*!*/)",
    '--tw-invert': "var(--tw-empty,/*!*/ /*!*/)",
    '--tw-saturate': "var(--tw-empty,/*!*/ /*!*/)",
    '--tw-sepia': "var(--tw-empty,/*!*/ /*!*/)",
    '--tw-drop-shadow': "var(--tw-empty,/*!*/ /*!*/)",
    '--tw-backdrop-blur': "var(--tw-empty,/*!*/ /*!*/)",
    '--tw-backdrop-brightness': "var(--tw-empty,/*!*/ /*!*/)",
    '--tw-backdrop-contrast': "var(--tw-empty,/*!*/ /*!*/)",
    '--tw-backdrop-grayscale': "var(--tw-empty,/*!*/ /*!*/)",
    '--tw-backdrop-hue-rotate': "var(--tw-empty,/*!*/ /*!*/)",
    '--tw-backdrop-invert': "var(--tw-empty,/*!*/ /*!*/)",
    '--tw-backdrop-opacity': "var(--tw-empty,/*!*/ /*!*/)",
    '--tw-backdrop-saturate': "var(--tw-empty,/*!*/ /*!*/)",
    '--tw-backdrop-sepia': "var(--tw-empty,/*!*/ /*!*/)",
  },
  '::backdrop': {
    '--tw-border-spacing-x': "0",
    '--tw-border-spacing-y': "0",
    '--tw-translate-x': "0",
    '--tw-translate-y': "0",
    '--tw-rotate': "0",
    '--tw-skew-x': "0",
    '--tw-skew-y': "0",
    '--tw-scale-x': "1",
    '--tw-scale-y': "1",
    '--tw-pan-x': "var(--tw-empty,/*!*/ /*!*/)",
    '--tw-pan-y': "var(--tw-empty,/*!*/ /*!*/)",
    '--tw-pinch-zoom': "var(--tw-empty,/*!*/ /*!*/)",
    '--tw-scroll-snap-strictness': "proximity",
    '--tw-ordinal': "var(--tw-empty,/*!*/ /*!*/)",
    '--tw-slashed-zero': "var(--tw-empty,/*!*/ /*!*/)",
    '--tw-numeric-figure': "var(--tw-empty,/*!*/ /*!*/)",
    '--tw-numeric-spacing': "var(--tw-empty,/*!*/ /*!*/)",
    '--tw-numeric-fraction': "var(--tw-empty,/*!*/ /*!*/)",
    '--tw-ring-offset-shadow': "0 0 #0000",
    '--tw-ring-shadow': "0 0 #0000",
    '--tw-shadow': "0 0 #0000",
    '--tw-shadow-colored': "0 0 #0000",
    '--tw-ring-inset': "var(--tw-empty,/*!*/ /*!*/)",
    '--tw-ring-offset-width': "0px",
    '--tw-ring-offset-color': "#fff",
    '--tw-ring-color': "rgb(59 130 246 / 0.5)",
    '--tw-blur': "var(--tw-empty,/*!*/ /*!*/)",
    '--tw-brightness': "var(--tw-empty,/*!*/ /*!*/)",
    '--tw-contrast': "var(--tw-empty,/*!*/ /*!*/)",
    '--tw-grayscale': "var(--tw-empty,/*!*/ /*!*/)",
    '--tw-hue-rotate': "var(--tw-empty,/*!*/ /*!*/)",
    '--tw-invert': "var(--tw-empty,/*!*/ /*!*/)",
    '--tw-saturate': "var(--tw-empty,/*!*/ /*!*/)",
    '--tw-sepia': "var(--tw-empty,/*!*/ /*!*/)",
    '--tw-drop-shadow': "var(--tw-empty,/*!*/ /*!*/)",
    '--tw-backdrop-blur': "var(--tw-empty,/*!*/ /*!*/)",
    '--tw-backdrop-brightness': "var(--tw-empty,/*!*/ /*!*/)",
    '--tw-backdrop-contrast': "var(--tw-empty,/*!*/ /*!*/)",
    '--tw-backdrop-grayscale': "var(--tw-empty,/*!*/ /*!*/)",
    '--tw-backdrop-hue-rotate': "var(--tw-empty,/*!*/ /*!*/)",
    '--tw-backdrop-invert': "var(--tw-empty,/*!*/ /*!*/)",
    '--tw-backdrop-opacity': "var(--tw-empty,/*!*/ /*!*/)",
    '--tw-backdrop-saturate': "var(--tw-empty,/*!*/ /*!*/)",
    '--tw-backdrop-sepia': "var(--tw-empty,/*!*/ /*!*/)",
  },
})"##### ; "1")]
fn test(input: &str, output: &str) {
    snapshot_inner(input, output)
}
