name: Continuous integration

on: [push, pull_request]

jobs:
  test:
    name: Snapshot Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - name: Set up Node 14
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - uses: Swatinem/rust-cache@v2
      - run: yarn
      - run: cargo test -- --ignored || true
