[package]
name = "swc-utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
swc_core = { version = "=0.40.16", features = ["common", "ecma_visit", "ecma_ast"] }
